<?php

namespace AppBundle\Repository;

/**
 * FrameworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameworkRepository extends \Doctrine\ORM\EntityRepository
{
	    public function byLanguage($id)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.language = :id')
                    ->orderBy('u.id')
                    ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
